package com.refi.usermanagement.domain;

import jakarta.persistence.*;

// The User entity represents a user in the system and is mapped to the 'users' table in the database.
@Entity
@Table(name = "users")
public class User {

    // Primary key for the user, auto-generated by the database.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Username of the user.
    private String username;

    // Email address of the user.
    private String email;

    // Password of the user (should be stored securely in production).
    private String password;

    // Default constructor required by JPA.
    public User() {}

    // Constructor to create a user with username, email, and password.
    public User(String username, String email, String password) {
        this.username = username;
        this.email = email;
        this.password = password;
    }

    // Getter for the user ID.
    public Long getId() {
        return id;
    }

    // Getter and setter for username.
    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    // Getter and setter for email.
    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    // Getter and setter for password.
    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
}
